// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OperationAccount.Data.SuperDigital.Context;

namespace OperationAccount.Data.SuperDigital.Migrations
{
    [DbContext(typeof(OperacaoDbContext))]
    partial class OperacaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SuperDigital")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OperationAccount.Business.SuperDigital.Models.ContaCorrente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("LancamentoId");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Saldo");

                    b.Property<Guid>("TitularId");

                    b.HasKey("Id");

                    b.ToTable("Conta");
                });

            modelBuilder.Entity("OperationAccount.Business.SuperDigital.Models.Lancamentos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ContaId");

                    b.Property<DateTime>("Data");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.ToTable("Lancamento");
                });

            modelBuilder.Entity("OperationAccount.Business.SuperDigital.Models.Titular", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ContaId");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContaId")
                        .IsUnique();

                    b.ToTable("Titular");
                });

            modelBuilder.Entity("OperationAccount.Business.SuperDigital.Models.Lancamentos", b =>
                {
                    b.HasOne("OperationAccount.Business.SuperDigital.Models.ContaCorrente", "ContaCorrente")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaId");
                });

            modelBuilder.Entity("OperationAccount.Business.SuperDigital.Models.Titular", b =>
                {
                    b.HasOne("OperationAccount.Business.SuperDigital.Models.ContaCorrente", "ContaCorrente")
                        .WithOne("Titular")
                        .HasForeignKey("OperationAccount.Business.SuperDigital.Models.Titular", "ContaId");
                });
#pragma warning restore 612, 618
        }
    }
}
